### ISSUE TITLE
[Known issue] Swift Compiler Error

### ISSUE THREAD

**Issue by zubco** [jkolb/Swiftish#3]
In Xcode Version 9.3 (9E145)

The fallowing files, won't compile because of compiler issue.
Quaternion.swift
Transform3.swift

Reported a [bug](https://bugs.swift.org/browse/SR-7530) for that.

**Comment by jkolb** [comment]
I've actually rewritten the library, but haven't pushed it up yet though. I took out support for everything but Float and Double to help simplify things since integers don't support trig functions and division truncates. This was a big API change though, but I feel it will make things easier in the long run and improves the time it takes to compile also.

I'll go ahead and put a new version right now.

**Comment by zubco** [comment]
Yeah, that solves the issue. Well done. 👍
Thank you for update.

Was using:
```
typealias Vector2i = Vector2<Int>
typealias Vector3i = Vector3<Int>
```
in my little game projects, because there was all arithmetic in place already.
In a lot of cases **Int** is enough for express game world, render it in chunks. And **Int** arithmetic tend to be faster.

I suppose I will define them now as a separate types for my use cases.

**Comment by jkolb** [comment]
I would be OK with adding Int support back but after battling with the compiler and doing some research I have learned that Swift seems to prefer them to be separate and distinct from the Float variants.

**Comment by jkolb** [comment]
What operations are you using? Just +, -, *?

**Comment by zubco** [comment]
Yes, those and Equatable conformance will do the job.
Thank you very much for interest, appreciate it. :sunglasses:

**Comment by jkolb** [comment]
It is done 😀

**Comment by zubco** [comment]
Awesome :smiley: :thumbsup:
Thank you very much!! :bow:
